version: "2.1"

services:
  mysql:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    image: mysql:5.7
  xqueue:
    container_name: xqueue
    image: edxops/xqueue:latest
    command: tail -f /dev/null
    volumes:
      - ..:/edx/app/xqueue/xqueue
    depends_on:
      - mysql
    environment:
      DB_HOST: "db"
      RABBIT_HOST: "rabbit"
