#!/bin/bash
DEFAULT_MAX=56

pycodestyle . | tee /tmp/pep8-xqueue.log
ERR=`grep -c ^ /tmp/pep8-xqueue.log `
MAX=${1-$DEFAULT_MAX}
if [ $ERR -gt $MAX ]; then
    echo "too many pep8 violations: $ERR (max is $MAX)"
    exit 1
else
    echo "$ERR pep8 violations in total (max is $MAX)"
    exit 0
fi
