# Generated by Django 2.2.24 on 2021-10-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission_queue', '0003_compound_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='queue_name',
            field=models.CharField(max_length=128),
        ),
    ]
