# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-03 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission_queue', '0003_compound_indexes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='submission',
            table='queue_submission',
        ),
    ]
