# Generated by Django 3.2.12 on 2022-03-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission_queue', '0004_remove_queue_name_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLearnerAssessmentDataTranslationAuditDepartmentTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_test', models.PositiveIntegerField(db_index=True)),
            ],
        ),
    ]
